myblog/main/routes.py
from flask import Blueprint, render_template, url_for, abort, redirect, flash, request
from flask_login import current_user, login_required
from myblog import db
from myblog.models import User, Project, Article, Reply, Tore
from myblog.main.forms import ProjectForm, ArticleForm, ReplyForm, ReplyReplyForm
from myblog.main.utils import is_new

main = Blueprint("main",__name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html', title='Home')


@main.route('/project/<user>',methods=["GET","POST"])
def project(user):
    username = User.query.filter_by(username=user).first_or_404()
    page = request.args.get('page',1,type=int)
    posts = Project.query.filter_by(user_id=username.id).order_by(Project.data_posted.desc()).paginate(per_page=3)
    next_url = url_for('main.project', user=username.username, page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.project', user=username.username, page=posts.prev_num) if posts.has_prev else None

    if posts.total == 0:
        new = False
    else:
        new = is_new(username)
    reply_form = ReplyForm()

    to_reply = ReplyReplyForm()
    replies = Reply.query
    toreplies = Tore.query

    if reply_form.submit1.data and reply_form.validate_on_submit():
        reply = Reply(content=reply_form.content.data, username=current_user.username, project_id=reply_form.id.data)
        db.session.add(reply)
        db.session.commit()
        return redirect(url_for('main.project', user=username.username,page=page))
    if to_reply.submit2.data and to_reply.validate_on_submit():
        reply_to = Tore(content=to_reply.content.data, username=current_user.username, reply_id=to_reply.id.data)
        db.session.add(reply_to)
        db.session.commit()
        return redirect(url_for('main.project', user=username.username, page=page))
    return render_template('project.html', title='Project',
                           user=username, project=True,
                           posts=posts, page=page,
                           next_url=next_url, prev_url=prev_url,
                           is_new=new, form=reply_form, replies=replies,
                           reply_form=to_reply,toreplies=toreplies)


@main.route('/project/new', methods=["GET","POST"])
@login_required
def new_project():
    project_form = ProjectForm()
    username = User.query.filter_by(username=current_user.username).first_or_404()
    if project_form.validate_on_submit():
        post = Project(title=project_form.title.data, content=project_form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your project has been created", 'success')
        return redirect(url_for('main.project', user=current_user.username))
    return render_template('create_project.html', title="New Project", form=project_form,
                                   user=username, legend= 'Upload a new project')


@main.route('/project/<user>/<int:post_id>', methods=["GET","POST"])
def aproject(user,post_id):
    post = Project.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    return render_template('aproject.html', title=post.title, post=post, user=username)


@main.route('/project/<user>/<int:post_id>/update', methods=["GET","POST"])
@login_required
def aproject_update(user,post_id):
    post = Project.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    project_form = ProjectForm()
    if post.author != current_user:
        abort(403)
    if project_form.validate_on_submit():
        post.title = project_form.title.data
        post.content = project_form.content.data
        db.session.commit()
        flash('Project has been successfully updated',"success")
        return redirect(url_for('main.aproject', user=username.username, post_id = post.id))
    elif request.method == 'GET':
        project_form.title.data = post.title
        project_form.content.data = post.content
    return render_template('create_project.html', title=post.title, post=post,
                                   user=username, form=project_form,
                                   legend= 'Update your project')


@main.route('/project/<user>/<int:post_id>/delete', methods=["POST"])
@login_required
def delete_aproject(user,post_id):
    post = Project.query.get_or_404(post_id)
    reply = Reply.query.filter_by(project_id=post.id).first()
    try:
        Tore.query.filter_by(reply_id = reply.id).delete()
    except:
        pass
    Reply.query.filter_by(project_id=post.id).delete()

    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your project has been successfully deleted', 'success')
    return redirect(url_for('main.project', user=current_user.username))


@main.route('/project/<user>/<int:reply_id>/delete_reply', methods=["POST"])
@login_required
def reply_delete(user,reply_id):
    username = User.query.filter_by(username=user).first_or_404()
    reply = Reply.query.filter_by(id=reply_id).first_or_404()
    try:
        Tore.query.filter_by(reply_id = reply.id).delete()
    except:
        pass
    if reply.username != current_user.username:
        abort(403)
    Reply.query.filter_by(id=reply.id).delete()
    db.session.commit()
    flash('Your comment has been successfully deleted','success')
    return redirect(url_for('main.project',user=username.username))


@main.route('/project/<user>/<int:tore_id>/d', methods=["POST"])
@login_required
def tore_delete(user,tore_id):
    username = User.query.filter_by(username=user).first_or_404()
    tore = Tore.query.filter_by(id=tore_id).first_or_404()
    if tore.username != current_user.username:
        abort(403)
    Tore.query.filter_by(id=tore.id).delete()
    db.session.commit()
    flash('Your reply has been successfully deleted','success')
    return redirect(url_for('main.project',user=username.username))

# --------------------------Article---------------------------------------

@main.route('/article/<user>',methods=["GET","POST"])
def article(user):
    username = User.query.filter_by(username=user).first_or_404()
    page = request.args.get('page',1,type=int)
    projects = Project.query.filter_by(user_id=username.id).all()
    posts = Article.query.filter_by(user_id=username.id).order_by(Article.data_posted.desc()).paginate(per_page=3)
    next_url = url_for('main.article', user=username.username, page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.article', user=username.username, page=posts.prev_num) if posts.has_prev else None
    if not projects:
        new = False
    else:
        new = is_new(username)
    return render_template('article.html', title='Article',
                           user=username, article=True,
                           posts=posts, page=page,
                           next_url=next_url, prev_url=prev_url,
                           is_new= new)


@main.route('/article/new', methods=["GET","POST"])
@login_required
def new_article():
    article_form = ArticleForm()
    username = User.query.filter_by(username=current_user.username).first_or_404()
    if article_form.validate_on_submit():
        post = Article(title=article_form.title.data, content=article_form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your article has been created", 'success')
        return redirect(url_for('main.article', user=current_user.username))
    return render_template('create_article.html', title="New Article", form=article_form,
                                   user=username, legend= 'Upload a new article')


@main.route('/article/<user>/<int:post_id>', methods=["GET","POST"])
def anarticle(user,post_id):
    post = Article.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    return render_template('anarticle.html', title=post.title, post=post, user=username)


@main.route('/article/<user>/<int:post_id>/update', methods=["GET","POST"])
@login_required
def anarticle_update(user,post_id):
    post = Article.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    article_form = ArticleForm()
    if post.author != current_user:
        abort(403)
    if article_form.validate_on_submit():
        post.title = article_form.title.data
        post.content = article_form.content.data
        db.session.commit()
        flash('Article has been successfully updated',"success")
        return redirect(url_for('main.anarticle', user=username.username, post_id = post.id))
    elif request.method == 'GET':
        article_form.title.data = post.title
        article_form.content.data = post.content
    return render_template('create_article.html', title=post.title, post=post,
                                   user=username, form=article_form,
                                   legend= 'Update your Article')


@main.route('/article/<user>/<int:post_id>/delete', methods=["POST"])
@login_required
def delete_anarticle(user,post_id):
    post = Article.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your article has been successfully deleted', 'success')
    return redirect(url_for('main.article', user=current_user.username))

myblog/users/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from myblog.users.forms import (RegistrationForm, LoginForm,
                                UpdateProfileForm ,ForgotEmailForm,
                                ResetPasswordForm)
from myblog import db, bcrypt
from myblog.models import User, Project
from flask_login import login_user, current_user, logout_user, login_required
from myblog.users.utils import save_picture, send_email

users = Blueprint("users",__name__)

@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email=login_form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            login_user(user, remember=login_form.remember.data)
            flash('Logged in Successfully','success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.project', user=current_user.username)) # depending on the user
        else:
            flash("The email or password you entered is incorrect" , 'danger')
    return render_template('login.html',form = login_form,title='Login')


@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    registration_form = RegistrationForm()
    if registration_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(registration_form.password.data).decode('utf-8')
        user = User(username=registration_form.username.data, email=registration_form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Account has been created! Please Login", 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form = registration_form,title='Register')


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/profile/', methods= ['GET','POST'])
@login_required
def profile():
    username = User.query.filter_by(username=current_user.username).first_or_404()
    image_file = url_for('static', filename='profile_picture/' + current_user.image_file)
    profile_form = UpdateProfileForm()
    if profile_form.validate_on_submit():
        if profile_form.picture.data:
            picture_file = save_picture(profile_form.picture.data)
            current_user.image_file = picture_file
        current_user.username = profile_form.username.data
        current_user.email = profile_form.email.data
        current_user.description = profile_form.description.data
        db.session.commit()
        flash('Your profile has been updated','success')
        return redirect(url_for('users.profile'))
    elif request.method == "GET":
        profile_form.username.data = current_user.username
        profile_form.email.data = current_user.email
        profile_form.description.data = current_user.description
    return render_template('profile.html',title='Profile',
                                   user=username, image_file=image_file, form =profile_form)


@users.route('/profile/<user>')
def static_profile(user):
    username = User.query.filter_by(username=user).first_or_404()
    return render_template('static_profile.html', title='Profile Info', user = username)


@users.route('/forgot_password', methods= ['GET','POST'])
def forgot_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    forgot_form = ForgotEmailForm()
    if forgot_form.validate_on_submit():
        user = User.query.filter_by(email=forgot_form.email.data).first()
        send_email(user)
        flash('Email has been sent to your account','success')
        return redirect(url_for('users.login'))
    return render_template('forgot_password.html',form=forgot_form, title='Forgot Password')


@users.route('/reset_password/<token>', methods= ['GET','POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token', 'danger')
        return redirect(url_for('users.forgot_password'))
    reset_form = ResetPasswordForm()
    if reset_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(reset_form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html',form=reset_form, title='Reset Password')


@users.route('/blog_history/<user>')
def blog_history(user):
    username = User.query.filter_by(username=user).first_or_404()
    posts = Project.query.filter_by(user_id=username.id).order_by(Project.data_posted.desc()).all()
    post_dict = {}
    for post in posts:
        post = [post.title, post.id, post.data_posted.strftime("%m %d %Y")]
        title, id, date = post
        if date in post_dict.keys():
            post_dict[date].append([id,title])
        else:
            post_dict[date] = [[id, title]]
    return render_template('blog_history.html', title='Blog history', posts=post_dict, user=username)

myblog/templates/includes/basic_profile.html
{#<img class="mr-3 article-img img-fluid rounded-circle" src="{{ url_for('static', filename='profile_picture/' + post.author.image_file) }}" alt="prifile image">#}

<div class="d-none d-md-block profile col-md-3 p-0 ">
    <div class="container-border">
        <div class="container card d-block col-11 mx-auto mt-1 container-profile" style="width: 18rem;">
          <div class="card-body">
            <img class="card-img-top img-fluid mb-2 rounded justify-content-center
                d-block mx-auto profile-img" src="{{ url_for('static', filename='profile_picture/' + user.image_file) }}"
                 alt="profile image">
            <h5 class="card-title text-center">{{ user.username }}'s Blog</h5>
            <p class="card-text">{{ user.description }}</p>
            <div class="profile-menu">
                <a class="text-muted profile-item" href="{{ url_for('users.static_profile', user=user.username) }}">Profile</a>
                <a class="text-muted profile-item" href="#"> Note</a>
            </div>
              {% if current_user.is_authenticated %}
                  {% if user.username == current_user.username %}
                      <a href="{{ url_for('users.profile', user=user.username ) }}"><small>Edit</small></a>
                  {% endif %}
              {% endif %}
          </div>
        </div>
        <div class="container col-11 mx-auto mt-1 container-border p-2 arrow_toggle mb-1">
            <a class="btn profile-cate" data-toggle="collapse" href="#menu" aria-expanded="True">
                <div class="d-flex justify-content-between">
                <span class="">Category</span>
                    <img class="profile-arrow" src="{{ url_for('static',filename='img/up-a.png') }}" alt="up-arrow">
                    <img style="display: none;" class="profile-arrow" src="{{ url_for('static',filename='img/down-a.png') }}" alt="down-arrow">
                </div>
            </a>
            <ul class="collapse show profile-ul p-0 m-0" id="menu">
                <li class=""><a href="{{ url_for('users.static_profile', user=user.username ) }}">Profile</a></li>
                <li class=""><a href="{{ url_for('users.blog_history', user=user.username ) }}">Blog History</a></li>
            </ul>
        </div>
    </div>
</div>

myblog/templates/includes/nav.html
<header>
    <nav class=" navbar navbar-light navbar-expand login-bar p-0 justify-content-end">
        <div class="navbar-nav">
            {% if current_user.is_authenticated %}
                <a class="nav-item nav-link active " href="{{ url_for('users.profile') }}">{{ current_user.username }}'s Profile</a>
                <a class="nav-item nav-link active " href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
                <a class="nav-item nav-link active " href="{{ url_for('users.register') }}">Register</a>
                <a class="nav-item nav-link active " href="{{ url_for('users.login') }}">Login</a>
            {% endif %}
        </div>

    </nav>
    <nav class= "navbar navbar-light navbar-expand shadow-sm profile-bar breadcrumb p-0 mb-2">
      <div class="container">
          <div class="navbar-nav">
              <a class="nav-item nav-link breadcrumb-item active
                 {% if project %} text-primary {% endif %}"
                 href="{{ url_for('main.project', user=user.username ) }}">Project
                  {% if is_new %} <small><span class="glow badge text-white badge-style">N</span></small>{% endif %}</a>
              <a class="nav-item nav-link breadcrumb-item active
                {% if article %} text-primary {% endif %}" href="{{ url_for('main.article',user=user.username) }}"> Article</a>
          </div>
            {% if current_user.is_authenticated %}
              {% if user.username == current_user.username %}
                  <div class="dropdown show">
                      <a class="nav-item nav-link btn nav_toggle" href="#"
                         data-toggle="dropdown" id="new_item" aria-haspopup="true" aria-expanded="false">Upload new<img  class="nav-arrow" src="{{ url_for('static',filename='img/down-a.png') }}" alt="down-arrow">
                          <img style="display: none;" class="nav-arrow" src="{{ url_for('static',filename='img/up-a.png') }}" alt="up-arrow">
                      </a>
                      <div class="dropdown-menu container-border" aria-labelledby="new_item" >
                          <a href="{{ url_for('main.new_project')}}" class="dropdown-item">Project</a>
                          <a href="{{ url_for('main.new_article')}}" class="dropdown-item">Ariticle</a>
                      </div>
                  </div>
              {% endif %}
            {% endif %}

      </div>
    </nav>
</header>