myblog/main/routes.py
from flask import Blueprint, render_template, url_for, abort, redirect, flash, request
from flask_login import current_user, login_required
from myblog import db
from myblog.models import User, Project, Article, Reply, Tore
from myblog.main.forms import ProjectForm, ArticleForm, ReplyForm, ReplyReplyForm
from myblog.main.utils import is_new

main = Blueprint("main",__name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html', title='Home')


@main.route('/project/<user>',methods=["GET","POST"])
def project(user):
    username = User.query.filter_by(username=user).first_or_404()
    page = request.args.get('page',1,type=int)
    posts = Project.query.filter_by(user_id=username.id).order_by(Project.data_posted.desc()).paginate(per_page=3)
    next_url = url_for('main.project', user=username.username, page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.project', user=username.username, page=posts.prev_num) if posts.has_prev else None

    if posts.total == 0:
        new = False
    else:
        new = is_new(username)
    reply_form = ReplyForm()

    to_reply = ReplyReplyForm()
    replies = Reply.query
    toreplies = Tore.query

    if reply_form.submit1.data and reply_form.validate_on_submit():
        reply = Reply(content=reply_form.content.data, username=current_user.username, project_id=reply_form.id.data)
        db.session.add(reply)
        db.session.commit()
        return redirect(url_for('main.project', user=username.username,page=page))
    if to_reply.submit2.data and to_reply.validate_on_submit():
        reply_to = Tore(content=to_reply.content.data, username=current_user.username, reply_id=to_reply.id.data)
        db.session.add(reply_to)
        db.session.commit()
        return redirect(url_for('main.project', user=username.username, page=page))
    return render_template('project.html', title='Project',
                           user=username, project=True,
                           posts=posts, page=page,
                           next_url=next_url, prev_url=prev_url,
                           is_new=new, form=reply_form, replies=replies,
                           reply_form=to_reply,toreplies=toreplies)


@main.route('/project/new', methods=["GET","POST"])
@login_required
def new_project():
    project_form = ProjectForm()
    username = User.query.filter_by(username=current_user.username).first_or_404()
    if project_form.validate_on_submit():
        post = Project(title=project_form.title.data, content=project_form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your project has been created", 'success')
        return redirect(url_for('main.project', user=current_user.username))
    return render_template('create_project.html', title="New Project", form=project_form,
                                   user=username, legend= 'Upload a new project')


@main.route('/project/<user>/<int:post_id>', methods=["GET","POST"])
def aproject(user,post_id):
    post = Project.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    return render_template('aproject.html', title=post.title, post=post, user=username)


@main.route('/project/<user>/<int:post_id>/update', methods=["GET","POST"])
@login_required
def aproject_update(user,post_id):
    post = Project.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    project_form = ProjectForm()
    if post.author != current_user:
        abort(403)
    if project_form.validate_on_submit():
        post.title = project_form.title.data
        post.content = project_form.content.data
        db.session.commit()
        flash('Project has been successfully updated',"success")
        return redirect(url_for('main.aproject', user=username.username, post_id = post.id))
    elif request.method == 'GET':
        project_form.title.data = post.title
        project_form.content.data = post.content
    return render_template('create_project.html', title=post.title, post=post,
                                   user=username, form=project_form,
                                   legend= 'Update your project')


@main.route('/project/<user>/<int:post_id>/delete', methods=["POST"])
@login_required
def delete_aproject(user,post_id):
    post = Project.query.get_or_404(post_id)
    reply = Reply.query.filter_by(project_id=post.id).first()
    try:
        Tore.query.filter_by(reply_id = reply.id).delete()
    except:
        pass
    Reply.query.filter_by(project_id=post.id).delete()

    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your project has been successfully deleted', 'success')
    return redirect(url_for('main.project', user=current_user.username))


@main.route('/project/<user>/<int:reply_id>/delete_reply', methods=["POST"])
@login_required
def reply_delete(user,reply_id):
    username = User.query.filter_by(username=user).first_or_404()
    reply = Reply.query.filter_by(id=reply_id).first_or_404()
    try:
        Tore.query.filter_by(reply_id = reply.id).delete()
    except:
        pass
    if reply.username != current_user.username:
        abort(403)
    Reply.query.filter_by(id=reply.id).delete()
    db.session.commit()
    flash('Your comment has been successfully deleted','success')
    return redirect(url_for('main.project',user=username.username))


@main.route('/project/<user>/<int:tore_id>/d', methods=["POST"])
@login_required
def tore_delete(user,tore_id):
    username = User.query.filter_by(username=user).first_or_404()
    tore = Tore.query.filter_by(id=tore_id).first_or_404()
    if tore.username != current_user.username:
        abort(403)
    Tore.query.filter_by(id=tore.id).delete()
    db.session.commit()
    flash('Your reply has been successfully deleted','success')
    return redirect(url_for('main.project',user=username.username))

# --------------------------Article---------------------------------------

@main.route('/article/<user>',methods=["GET","POST"])
def article(user):
    username = User.query.filter_by(username=user).first_or_404()
    page = request.args.get('page',1,type=int)
    projects = Project.query.filter_by(user_id=username.id).all()
    posts = Article.query.filter_by(user_id=username.id).order_by(Article.data_posted.desc()).paginate(per_page=3)
    next_url = url_for('main.article', user=username.username, page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.article', user=username.username, page=posts.prev_num) if posts.has_prev else None
    if not projects:
        new = False
    else:
        new = is_new(username)
    return render_template('article.html', title='Article',
                           user=username, article=True,
                           posts=posts, page=page,
                           next_url=next_url, prev_url=prev_url,
                           is_new= new)


@main.route('/article/new', methods=["GET","POST"])
@login_required
def new_article():
    article_form = ArticleForm()
    username = User.query.filter_by(username=current_user.username).first_or_404()
    if article_form.validate_on_submit():
        post = Article(title=article_form.title.data, content=article_form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your article has been created", 'success')
        return redirect(url_for('main.article', user=current_user.username))
    return render_template('create_article.html', title="New Article", form=article_form,
                                   user=username, legend= 'Upload a new article')


@main.route('/article/<user>/<int:post_id>', methods=["GET","POST"])
def anarticle(user,post_id):
    post = Article.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    return render_template('anarticle.html', title=post.title, post=post, user=username)


@main.route('/article/<user>/<int:post_id>/update', methods=["GET","POST"])
@login_required
def anarticle_update(user,post_id):
    post = Article.query.get_or_404(post_id)
    username = User.query.filter_by(username=user).first_or_404()
    article_form = ArticleForm()
    if post.author != current_user:
        abort(403)
    if article_form.validate_on_submit():
        post.title = article_form.title.data
        post.content = article_form.content.data
        db.session.commit()
        flash('Article has been successfully updated',"success")
        return redirect(url_for('main.anarticle', user=username.username, post_id = post.id))
    elif request.method == 'GET':
        article_form.title.data = post.title
        article_form.content.data = post.content
    return render_template('create_article.html', title=post.title, post=post,
                                   user=username, form=article_form,
                                   legend= 'Update your Article')


@main.route('/article/<user>/<int:post_id>/delete', methods=["POST"])
@login_required
def delete_anarticle(user,post_id):
    post = Article.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your article has been successfully deleted', 'success')
    return redirect(url_for('main.article', user=current_user.username))

myblog/users/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from myblog.users.forms import (RegistrationForm, LoginForm,
                                UpdateProfileForm ,ForgotEmailForm,
                                ResetPasswordForm)
from myblog import db, bcrypt
from myblog.models import User, Project
from flask_login import login_user, current_user, logout_user, login_required
from myblog.users.utils import save_picture, send_email

users = Blueprint("users",__name__)

@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email=login_form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, login_form.password.data):
            login_user(user, remember=login_form.remember.data)
            flash('Logged in Successfully','success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.project', user=current_user.username)) # depending on the user
        else:
            flash("The email or password you entered is incorrect" , 'danger')
    return render_template('login.html',form = login_form,title='Login')


@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    registration_form = RegistrationForm()
    if registration_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(registration_form.password.data).decode('utf-8')
        user = User(username=registration_form.username.data, email=registration_form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Account has been created! Please Login", 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form = registration_form,title='Register')


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/profile/', methods= ['GET','POST'])
@login_required
def profile():
    username = User.query.filter_by(username=current_user.username).first_or_404()
    image_file = url_for('static', filename='profile_picture/' + current_user.image_file)
    profile_form = UpdateProfileForm()
    if profile_form.validate_on_submit():
        if profile_form.picture.data:
            picture_file = save_picture(profile_form.picture.data)
            current_user.image_file = picture_file
        current_user.username = profile_form.username.data
        current_user.email = profile_form.email.data
        current_user.description = profile_form.description.data
        db.session.commit()
        flash('Your profile has been updated','success')
        return redirect(url_for('users.profile'))
    elif request.method == "GET":
        profile_form.username.data = current_user.username
        profile_form.email.data = current_user.email
        profile_form.description.data = current_user.description
    return render_template('profile.html',title='Profile',
                                   user=username, image_file=image_file, form =profile_form)


@users.route('/profile/<user>')
def static_profile(user):
    username = User.query.filter_by(username=user).first_or_404()
    return render_template('static_profile.html', title='Profile Info', user = username)


@users.route('/forgot_password', methods= ['GET','POST'])
def forgot_password():
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    forgot_form = ForgotEmailForm()
    if forgot_form.validate_on_submit():
        user = User.query.filter_by(email=forgot_form.email.data).first()
        send_email(user)
        flash('Email has been sent to your account','success')
        return redirect(url_for('users.login'))
    return render_template('forgot_password.html',form=forgot_form, title='Forgot Password')


@users.route('/reset_password/<token>', methods= ['GET','POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.project', user=current_user.username))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token', 'danger')
        return redirect(url_for('users.forgot_password'))
    reset_form = ResetPasswordForm()
    if reset_form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(reset_form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated", 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html',form=reset_form, title='Reset Password')


@users.route('/blog_history/<user>')
def blog_history(user):
    username = User.query.filter_by(username=user).first_or_404()
    posts = Project.query.filter_by(user_id=username.id).order_by(Project.data_posted.desc()).all()
    post_dict = {}
    for post in posts:
        post = [post.title, post.id, post.data_posted.strftime("%m %d %Y")]
        title, id, date = post
        if date in post_dict.keys():
            post_dict[date].append([id,title])
        else:
            post_dict[date] = [[id, title]]
    return render_template('blog_history.html', title='Blog history', posts=post_dict, user=username)

myblog/templates/anarticle.html
{% extends "index.html" %}
{% block main %}
        <div class="container-border">
        <article class="container">
            <h3>{{ post.title }}</h3>
            <div class="media border-bottom mb-2 pb-1 ">
                <img class="mr-3 article-img img-fluid rounded-circle" src="{{ url_for('static', filename='profile_picture/' + post.author.image_file) }}" alt="prifile image">
                <div class="media-body ">{{ post.author.username }}
                </div>
                {% if post.author == current_user %}
                    <div class="d-inline">
                        <small><a href="{{ url_for('main.anarticle_update', user = current_user.username,
                           post_id = post.id) }}" class="text-muted">Update</a></small>
                        <small><a href="#" class="text-muted"
                        data-toggle="modal" data-target="#Delete-Modal"> Delete</a></small>
                    </div>
                {% endif %}
                <span class="ml-2 text-muted ">{{ post.data_posted.strftime("%m/%d/%Y") }}</span>
            </div>
            <p class="article-content">{{ post.content }}</p>
        </article>
        </div>

    <!-- Modal -->
    <div class="modal fade" id="Delete-Modal" tabindex="-1" role="dialog" aria-labelledby="Delete-Modal" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header border-bottom-0 pb-0">
            <h5 class="modal-title" id="Delete-Modal-Label">Are you sure?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer border-top-0">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('main.delete_anarticle', post_id=post.id, user=current_user.username) }}" method="post">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
</div>
{% endblock main %}

myblog/templates/aproject.html
{% extends "index.html" %}
{% block main %}
        <div class="container-border">
            <article class="container">
                <h3>{{ post.title }}</h3>
                <div class="media border-bottom mb-2 pb-1 ">
                    <img class="mr-3 article-img img-fluid rounded-circle" src="{{ url_for('static', filename='profile_picture/' + post.author.image_file) }}" alt="prifile image">
                    <div class="media-body ">{{ post.author.username }}
                    </div>
                    {% if post.author == current_user %}
                        <div class="d-inline">
                            <small><a href="{{ url_for('main.aproject_update', user = current_user.username,
                               post_id = post.id) }}" class="text-muted">Update</a></small>
                            <small><a href="#" class="text-muted"
                            data-toggle="modal" data-target="#Delete-Modal"> Delete</a></small>
                        </div>
                    {% endif %}
                    <span class="ml-2 text-muted ">{{ post.data_posted.strftime("%m/%d/%Y") }}</span>
                </div>
                <p class="article-content">{{ post.content }}</p>
            </article>
        </div>

    <!-- Modal -->
    <div class="modal fade" id="Delete-Modal" tabindex="-1" role="dialog" aria-labelledby="Delete-Modal" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header border-bottom-0 pb-0">
            <h5 class="modal-title" id="Delete-Modal-Label">Are you sure?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer border-top-0">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('main.delete_aproject', post_id=post.id, user=current_user.username) }}" method="post">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock main %}

myblog/templates/article.html
{% extends "index.html" %}
{% block main %}
    {% if posts.total == 0  %}
        <div class="container-border text-center m-2">
            There is currently no content in this section
        </div>
    {% else %}
        <div class="container-border">
            {% for post in posts.items %}
                <article class="container">
                    <h3><a href="{{ url_for('main.anarticle', post_id=post.id, user=user.username) }}">{{ post.title }}</a></h3>
                    <div class="media border-bottom mb-2 pb-1 ">
                        <img class="mr-3 article-img img-fluid rounded-circle" src="{{ url_for('static', filename='profile_picture/' + post.author.image_file) }}" alt="prifile image">
                        <div class="media-body ">{{ post.author.username }}
                        </div>
                        <span class="ml-2 text-muted ">{{ post.data_posted.strftime("%m/%d/%Y") }}</span>
                    </div>
                    <p class="article-content">{{ post.content }}</p>
                </article>
            {% endfor %}
                <div class="container row justify-content-center mb-3 align-items-baseline">
                    {% if prev_url %}
                    <a class="text-dark" href="{{ prev_url }}">prev</a>
                    {% endif %}

                    {% for page in posts.iter_pages(left_edge=0, right_edge=0, left_current=2,right_current=3) %}
                        {% if page %}
                            {% if posts.page == page %}
                                <a class="btn page-active-outline" href="{{ url_for('main.project', user= user.username,
                                    page = page)}}">{{ page }}</a>
                            {% else %}
                                <a class="btn page-outline" href="{{ url_for('main.project', user= user.username,
                                    page = page)}}">{{ page }}</a>
                            {% endif %}
                        {% else %}
                        {% endif %}
                    {% endfor %}

                    {% if next_url %}
                    <a class="text-dark" href="{{ next_url }}">next</a>
                    {% endif %}
                </div>
        </div>
    {% endif %}
{% endblock main %}

myblog/templates/blog_history.html
{% extends "index.html" %}
{% block main %}
    <div class="container container-border">
    {% for date in posts.keys() %}
        <h2 class="font-italic text-muted border-bottom">{{ date }}</h2>
        {% for id, title in posts[date] %}
            <ul class="p-0 m-0 list-unstyled">
                <li><a href="{{ url_for('main.aproject', user=user.username, post_id=id) }}">{{ title }}</a></li>
            </ul>
        {% endfor %}
    {% endfor %}
    </div>
{% endblock main %}

myblog/templates/create_article.html
{% extends "index.html" %}
{% block main %}
    <div class="container-border">
        <div class="container">
            <div class="row">
                <form class="col-sm-12" method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend>{{ legend }}</legend>
                        <div class="form-group">
                            {{ form.title.label() }}
                            {% if form.title.errors %}
                                {{ form.title(class="form-control is-invalid",placeholder='Title') }}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.title(class="form-control",placeholder='Title') }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.content.label() }}
                            {% if form.content.errors %}
                                {{ form.content(class="form-control is-invalid",style="height: 200px;") }}
                                <div class="invalid-feedback">
                                    {% for error in form.content.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.content(class="form-control",style="height: 200px;") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-0">
                            {{ form.submit(class='btn btn-block btn-info') }}
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>



{% endblock main %}

myblog/templates/create_project.html
{% extends "index.html" %}
{% block main %}
    <div class="container-border">
        <div class="container">
            <div class="row">
                <form class="col-sm-12" method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend>{{ legend }}</legend>
                        <div class="form-group">
                            {{ form.title.label() }}
                            {% if form.title.errors %}
                                {{ form.title(class="form-control is-invalid",placeholder='Title') }}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.title(class="form-control",placeholder='Title') }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.content.label() }}
                            {% if form.content.errors %}
                                {{ form.content(class="form-control is-invalid",style="height: 200px;") }}
                                <div class="invalid-feedback">
                                    {% for error in form.content.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.content(class="form-control",style="height: 200px;") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-0">
                            {{ form.submit(class='btn btn-block btn-info') }}
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>



{% endblock main %}

myblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="home-font">
        <img class="card-img img-fluid vh-100" src="{{ url_for('static', filename='img/back.jpg') }}" alt="background-img">
        <div class="position-fixed home-body">
            <div class="d-flex flex-column align-items-end ">
                <a class="home-a" href="{{ url_for('users.login') }}">Login</a>
                <h1 class="home-title">Create your own blog</h1>
                <a  class="btn btn-primary" href="{{ url_for('users.register') }}">Let's get started</a>
            </div>
        </div>
    </div>
{% endblock content %}

myblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="row vh-100 justify-content-center align-items-center">
            <form class="col-sm-6 container-border" method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend>Log In</legend>
                    <div class="form-group">
                        {{ form.email.label() }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid",placeholder='Email') }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control",placeholder='Email') }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label() }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid",placeholder='Password') }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control",placeholder='Password') }}
                        {% endif %}
                    </div>
                    {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                    <small>{{ message }}</small>
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                    <div class="custom-control custom-switch mb-3">
                        {{ form.remember(class="custom-control-input", type="checkbox", id='switch') }}
                        {{ form.remember.label(class="custom-control-label", for='switch') }}
                    </div>
                    <div class="form-group mb-0">
                        {{ form.submit(class='btn btn-block btn-info') }}
                    </div>
                </fieldset>
                <div class="mt-0">
                    <small class="text-muted">
                        Forgot your <a href="{{ url_for('users.forgot_password')}}">Password?</a> <small>or</small> <a href="{{ url_for('users.register') }}">Create-account</a>
                    </small>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

myblog/templates/static_profile.html
{% extends "index.html" %}
{% block main %}
    <div class="container-border">
        <div class="media">
            <img class="d-flex rounded m-3 img-fluid" style="width: 100px;" alt="profile_pic"
                 src="{{ url_for('static', filename='profile_picture/' + user.image_file) }}">
            <div class="media-body m-3 ml-0">
                <h3>{{ user.username }}</h3>
                <p class="text-muted">{{ user.email }}</p>
                <p class="">{{ user.description }}</p>
            </div>
        </div>
    </div>

{% endblock main %}